CREATE USER BYUL IDENTIFIED BY "BYUL";
GRANT CREATE SESSION TO BYUL;
GRANT DBA TO BYUL;
GRANT CONNECT, RESOURCE TO BYUL;
GRANT CREATE ANY SYNONYM, CREATE ANY VIEW TO BYUL;

--DROP USER BYUL CASCADE;
--ALTER TRIGGER SYS.XDB_PI_TRIG COMPILE;
--ALTER TRIGGER SYS.XDB_PI_TRIG DISABLE;