CREATE TABLE ACCOUNTS (
    ACT_CODE    NVARCHAR2(500) PRIMARY KEY,
    ACT_LNAME   NVARCHAR2(500) NOT NULL,
    ACT_FNAME   NVARCHAR2(500) NOT NULL,
    ACT_PASS    NVARCHAR2(64) NOT NULL,
    ACT_TEL     NVARCHAR2(500) UNIQUE, --UNIQUE : 중복 방지
    ACT_EMAIL   NVARCHAR2(500) UNIQUE,
    ACT_POST    NVARCHAR2(500) NOT NULL,
    ACT_ADDRESS NVARCHAR2(500) UNIQUE,
    ACT_REGDATE DATE DEFAULT SYSDATE NOT NULL,
    ACT_TYPE    NUMBER(1) DEFAULT 1 NOT NULL CHECK (ACT_TYPE IN(0, 1)) -- 0 관리자, 1 고객
)
TABLESPACE USERS;

CREATE TABLE ACCESSLOG ( -- 접속 기록
    ASL_ACTCODE NVARCHAR2(500),
    ASL_DATE    DATE DEFAULT SYSDATE,
    ASL_ACTION  NUMBER(1) CHECK (ASL_ACTION IN(-1, 1)), -- 1 로그인 -1 로그아웃
    PRIMARY KEY ( ASL_ACTCODE,
                  ASL_DATE,
                  ASL_ACTION ),
    FOREIGN KEY ( ASL_ACTCODE )
        REFERENCES ACCOUNTS ( ACT_CODE )
)
TABLESPACE USERS;

CREATE TABLE CATEGORIES ( -- 상위 카테고리
    CA_CODE NCHAR(2) PRIMARY KEY,
    CA_NAME NVARCHAR2(100) UNIQUE
)
TABLESPACE USERS;

CREATE TABLE SUBCATEGORIES ( -- 하위 카테고리
    SC_CACODE NCHAR(2),
    SC_CODE   NCHAR(2),
    SC_NAME   NVARCHAR2(100) UNIQUE,
    PRIMARY KEY ( SC_CACODE,
                  SC_CODE ),
    FOREIGN KEY ( SC_CACODE )
        REFERENCES CATEGORIES ( CA_CODE )
)
TABLESPACE USERS;

CREATE TABLE BRAND ( -- 브랜드
    BR_CODE NCHAR(2) PRIMARY KEY,
    BR_NAME NVARCHAR2(100) UNIQUE
)
TABLESPACE USERS;

CREATE TABLE MADE ( -- 제조국
    MD_CODE NCHAR(2) PRIMARY KEY,
    MD_NAME NVARCHAR2(100) UNIQUE
)
TABLESPACE USERS;

CREATE TABLE PRODUCT ( -- 상품
    PRD_CODE     NCHAR(4) PRIMARY KEY,
    PRD_NAME     NVARCHAR2(200) NOT NULL,
    PRD_BRCODE   NCHAR(2),
    PRD_SCCACODE NCHAR(2),
    PRD_SCCODE   NCHAR(2),
    PRD_PRICE    NUMBER(6) DEFAULT - 1 NOT NULL, -- 최대 999,999 엔
    PRD_MDCODE   NCHAR(2),
    PRD_CONTENT  NVARCHAR2(2000),
    PRD_VISIBLE  NUMBER(1) DEFAULT 1 NOT NULL CHECK (PRD_VISIBLE IN(0, 1)), -- 1 공개 0 비공개
    PRD_REGDATE  DATE DEFAULT SYSDATE NOT NULL,
    FOREIGN KEY ( PRD_SCCACODE,
                  PRD_SCCODE )
        REFERENCES SUBCATEGORIES ( SC_CACODE,
                                   SC_CODE ),
    FOREIGN KEY ( PRD_BRCODE )
        REFERENCES BRAND ( BR_CODE ),
    FOREIGN KEY ( PRD_MDCODE )
        REFERENCES MADE ( MD_CODE )
)
TABLESPACE USERS;

CREATE SEQUENCE PRD_CODE
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE TABLE COLOR ( -- 색상
    CLR_CODE NCHAR(3) PRIMARY KEY,
    CLR_NAME NVARCHAR2(100) UNIQUE
)
TABLESPACE USERS;

CREATE TABLE SIZING ( -- 사이즈
    SZ_CODE NCHAR(3) PRIMARY KEY,
    SZ_NAME NVARCHAR2(100) UNIQUE
)
TABLESPACE USERS;

CREATE TABLE PRODUCTVARIANTS ( -- 상품 상세
    PVR_PRDCODE NCHAR(4),
    PVR_CLRCODE NCHAR(3),
    PVR_SZCODE  NCHAR(3),
    PVR_STOCK   NUMBER(3) DEFAULT - 1 NOT NULL, -- 재고, -1은 초기값을 의미 (미수정)
    PRIMARY KEY ( PVR_PRDCODE,
                  PVR_CLRCODE,
                  PVR_SZCODE ),
    FOREIGN KEY ( PVR_PRDCODE )
        REFERENCES PRODUCT ( PRD_CODE ),
    FOREIGN KEY ( PVR_CLRCODE )
        REFERENCES COLOR ( CLR_CODE ),
    FOREIGN KEY ( PVR_SZCODE )
        REFERENCES SIZING ( SZ_CODE )
)
TABLESPACE USERS;

CREATE TABLE PRODUCTFILES ( -- 상품 이미지 파일
    PFL_PRDCODE NCHAR(4),
    PFL_CODE    NUMBER(2),
    PFL_NAME    NVARCHAR2(50) NOT NULL,
    PFL_PATH    NVARCHAR2(100) NOT NULL,
    PFL_CLRCODE NCHAR(2),
    PRIMARY KEY ( PFL_PRDCODE, -- 상품코드 + 파일코드로 PRIMARY KEY
                  PFL_CODE ),
    FOREIGN KEY ( PFL_PRDCODE )
        REFERENCES PRODUCT ( PRD_CODE ),
    FOREIGN KEY ( PFL_CLRCODE )
        REFERENCES COLOR ( CLR_CODE )
)
TABLESPACE USERS;

CREATE TABLE ORDERS ( -- 주문
    ORD_CODE    NCHAR(5) PRIMARY KEY,
    ORD_ACTCODE NVARCHAR2(500),
    ORD_DATE    DATE DEFAULT SYSDATE NOT NULL,
    ORD_STATE   NUMBER(1) DEFAULT 0 NOT NULL, --0 장바구니, 1 주문완료
    FOREIGN KEY ( ORD_ACTCODE )
        REFERENCES ACCOUNTS ( ACT_CODE )
)
TABLESPACE USERS;

CREATE TABLE ORDERDETAIL ( -- 주문 상세
    ODT_ORDCODE    NCHAR(5),
    ODT_PVRPRDCODE NCHAR(4),
    ODT_PVRCLRCODE NCHAR(2),
    ODT_PVRSZCODE  NCHAR(2),
    ODT_QUANTITY   NUMBER(3) DEFAULT - 1 NOT NULL,
    PRIMARY KEY ( ODT_ORDCODE,
                  ODT_PVRPRDCODE,
                  ODT_PVRCLRCODE,
                  ODT_PVRSZCODE ),
    FOREIGN KEY ( ODT_ORDCODE )
        REFERENCES ORDERS ( ORD_CODE ),
    FOREIGN KEY ( ODT_PVRPRDCODE,
                  ODT_PVRCLRCODE,
                  ODT_PVRSZCODE )
        REFERENCES PRODUCTVARIANTS ( PVR_PRDCODE,
                                     PVR_CLRCODE,
                                     PVR_SZCODE )
)
TABLESPACE USERS;

CREATE TABLE VIEWHISTORY ( -- 조회기록, 위시리스트
    VHS_ACTCODE NVARCHAR2(500),
    VHS_PRDCODE NCHAR(4),
    VHS_DATE    DATE DEFAULT SYSDATE NOT NULL,
    VHS_ISWISH  NUMBER(1) DEFAULT 0 NOT NULL CHECK (VHS_ISWISH IN(0, 1)), -- 1 위시리스트인 상품 , 0 아닌 상품
    PRIMARY KEY ( VHS_ACTCODE,
                  VHS_PRDCODE ),
    FOREIGN KEY ( VHS_ACTCODE )
        REFERENCES ACCOUNTS ( ACT_CODE ),
    FOREIGN KEY ( VHS_PRDCODE )
        REFERENCES PRODUCT ( PRD_CODE )
)
TABLESPACE USERS;

--DROP TABLE ACCESSLOG CASCADE CONSTRAINTS;
--DROP TABLE BRAND CASCADE CONSTRAINTS;
--DROP TABLE CATEGORIES CASCADE CONSTRAINTS;
--DROP TABLE COLOR CASCADE CONSTRAINTS;
--DROP TABLE COUNTRY CASCADE CONSTRAINTS;
--DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
--DROP TABLE MEMBERSHIP CASCADE CONSTRAINTS;
--DROP TABLE PRODUCT CASCADE CONSTRAINTS;
--DROP TABLE PRODUCTFILES CASCADE CONSTRAINTS;
--DROP TABLE PRODUCTVARIANTS CASCADE CONSTRAINTS;
--DROP TABLE SIZING CASCADE CONSTRAINTS;
--DROP TABLE ORDERS CASCADE CONSTRAINTS;
--DROP TABLE ORDERDETAIL CASCADE CONSTRAINTS;
--DROP TABLE SUBCATEGORIES CASCADE CONSTRAINTS;
--DROP TABLE VIEWHISTORY CASCADE CONSTRAINTS;
--DROP PUBLIC SYNONYM ASL;
--DROP PUBLIC SYNONYM ACT;
--DROP PUBLIC SYNONYM BR;
--DROP PUBLIC SYNONYM CA;
--DROP PUBLIC SYNONYM CLR;
--DROP PUBLIC SYNONYM MD;
--DROP PUBLIC SYNONYM ODT;
--DROP PUBLIC SYNONYM ORD;
--DROP PUBLIC SYNONYM PRD;
--DROP PUBLIC SYNONYM PFL;
--DROP PUBLIC SYNONYM PVR;
--DROP PUBLIC SYNONYM SZ;
--DROP PUBLIC SYNONYM SC;
--DROP PUBLIC SYNONYM VHS;
CREATE PUBLIC SYNONYM ASL FOR ACCESSLOG;
CREATE PUBLIC SYNONYM ACT FOR ACCOUNTS;
CREATE PUBLIC SYNONYM BR FOR BRAND;
CREATE PUBLIC SYNONYM CA FOR CATEGORIES;
CREATE PUBLIC SYNONYM CLR FOR COLOR;
CREATE PUBLIC SYNONYM MAD FOR MADE;
CREATE PUBLIC SYNONYM ODT FOR ORDERDETAIL;
CREATE PUBLIC SYNONYM ORD FOR ORDERS;
CREATE PUBLIC SYNONYM PRD FOR PRODUCT;
CREATE PUBLIC SYNONYM PFL FOR PRODUCTFILES;
CREATE PUBLIC SYNONYM PVR FOR PRODUCTVARIANTS;
CREATE PUBLIC SYNONYM SZ FOR SIZING;
CREATE PUBLIC SYNONYM SC FOR SUBCATEGORIES;
CREATE PUBLIC SYNONYM VHS FOR VIEWHISTORY;
